version: '3.5'
services:
  redis:
    image: redis:latest
    container_name: ${PROJECT_PREFIX}_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
    redis_data:
      driver: local
